// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuuapuzwnghgdkskkvhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1dWFwdXp3bmdoZ2Rrc2trdmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5ODA4NjcsImV4cCI6MjA3OTU1Njg2N30.gPFiTBTwUVL16bMv6_kkyGqY2rMbinm_k7eEc2-9eK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});